# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3dc3805c470eee066823e61607b16df54b157203674fdd0287c0ff24f90b3d0472a6ec623e7157e896d05b3418c64e89f8f5259688665bbba61db250c854298a

test:
  secret_key_base: 4967ffd8a605e7024e3625cd44e83c1a06e1e13b36d48f6c9c4762745fdaadee690a9d58797baa357a00afca7607dcd6c0d4d8e88357b1664b9c7a3fea607ae2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
